stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
  #- test

build-a:
stage: build
script:
     - ls
     - echo "yop"
     - cd nxc
     - ls
     
deploy-a:
stage: deploy
script:
  - echo "yop"  
   
# build-nxc:
#   stage: build
#   script:
#     - nix --version
#     - nxc --version 
#     - cd nxc
#     - nxc build -f g5k-nfs-store
    
# deploy-nxc:
#   #- add test node file and 
#   - nxc start -m var/NXC_OAR_$(cat var/NXC_OAR_JOB_ID).stdout
# #      - nxc driver test_success.py
# #      - nxc driver test_fail.py
